"""Static metadata for all supported image generation models.

Source rankings: Artificial Analysis Text-to-Image Leaderboard (Elo-based),
blind pairwise user preference tests (millions of votes).
Pricing: fal.ai pricing page (März 2026).
Last synced: 2026-03-11
"""
from __future__ import annotations
from typing import Optional

IMAGE_MODELS_CATALOG: list[dict] = [
    # ── RANG #1 — GPT Image 1.5 ──────────────────────────────────────────────
    {
        "slug": "gpt_image_15",
        "name": "GPT Image 1.5 (High)",
        "provider_type": "fal_generic",
        "fal_endpoint": "fal-ai/gpt-image-1.5",
        "price_per_image": 0.133,
        "price_label": "$0.133 / Bild",
        "cost_tier": "expensive",
        "elo_score": 1268,
        "elo_rank": 1,
        "elo_source": "Artificial Analysis Arena (März 2026)",
        "quality_stars": 5,
        "speed_seconds": 12,
        "best_for": ["hero", "premium"],
        "description": "OpenAI GPT Image 1.5, Rang #1 weltweit (Elo 1268). Absolute Spitzenqualität.",
        "badge": "Rang #1 Weltweit",
        "badge_color": "#FFD700",
        "is_default": False,
        "is_preview": False,
        "cost_note": "⚠️ Teuer: $133/1.000 Bilder — nur für kritische Assets",
    },
    # ── RANG #2 — Nano Banana 2 ───────────────────────────────────────────────
    {
        "slug": "gemini_flash",
        "name": "Nano Banana 2 (Gemini 3.1 Flash)",
        "provider_type": "fal_generic",
        "fal_endpoint": "fal-ai/nano-banana-2",
        "price_per_image": 0.067,
        "price_label": "$0.067 / Bild",
        "cost_tier": "premium",
        "elo_score": 1260,
        "elo_rank": 2,
        "elo_source": "Artificial Analysis Arena (März 2026)",
        "quality_stars": 5,
        "speed_seconds": 8,
        "best_for": ["hero", "portrait", "general"],
        "description": "Rang #2 weltweit (Elo 1260). Googles Gemini 3.1 Flash — bestes Preis-Qualitäts-Verhältnis im Top-Segment.",
        "badge": "Rang #2",
        "badge_color": "#C0C0C0",
        "is_default": False,
        "is_preview": False,
    },
    # ── RANG #4 — Nano Banana Pro ─────────────────────────────────────────────
    {
        "slug": "gemini_pro",
        "name": "Nano Banana Pro (Gemini 3 Pro)",
        "provider_type": "fal_generic",
        "fal_endpoint": "fal-ai/nano-banana-pro",
        "price_per_image": 0.134,
        "price_label": "$0.134 / Bild",
        "cost_tier": "expensive",
        "elo_score": 1217,
        "elo_rank": 4,
        "elo_source": "Artificial Analysis Arena (März 2026)",
        "quality_stars": 5,
        "speed_seconds": 10,
        "best_for": ["hero", "premium"],
        "description": "Rang #4 weltweit (Elo 1217). Googles Gemini 3 Pro — maximale Bildqualität.",
        "badge": "Rang #4",
        "badge_color": "#CD7F32",
        "is_default": False,
        "is_preview": False,
        "cost_note": "⚠️ Teuer: $134/1.000 Bilder — nur für kritische Assets",
    },
    # ── RANG #5 — FLUX.2 Max ─────────────────────────────────────────────────
    {
        "slug": "flux2_max",
        "name": "FLUX.2 Max",
        "provider_type": "fal_generic",
        "fal_endpoint": "fal-ai/flux-2-max",
        "price_per_image": 0.070,
        "price_label": "$0.07 / Bild",
        "cost_tier": "premium",
        "elo_score": 1206,
        "elo_rank": 5,
        "elo_source": "Artificial Analysis Arena (März 2026)",
        "quality_stars": 5,
        "speed_seconds": 8,
        "best_for": ["hero", "portrait", "general"],
        "description": "FLUX.2 Max, Rang #5 weltweit (Elo 1206). Black Forest Labs' stärkstes Modell — beste FLUX-Qualität.",
        "badge": "Rang #5",
        "badge_color": "#4285F4",
        "is_default": False,
        "is_preview": False,
    },
    # ── RANG #6 — FLUX.2 Pro (Empfehlung) ────────────────────────────────────
    {
        "slug": "flux2_pro",
        "name": "FLUX.2 Pro",
        "provider_type": "fal_generic",
        "fal_endpoint": "fal-ai/flux-2-pro",
        "price_per_image": 0.030,
        "price_label": "$0.03 / Bild",
        "cost_tier": "standard",
        "elo_score": 1190,
        "elo_rank": 6,
        "elo_source": "Artificial Analysis Arena (März 2026)",
        "quality_stars": 5,
        "speed_seconds": 5,
        "best_for": ["hero", "portrait", "general"],
        "description": "Bestes Preis-Leistungs-Verhältnis 2026. Rang #6 weltweit (Elo 1190). Produktionsreif, kein Tuning nötig.",
        "badge": "Empfohlen",
        "badge_color": "#6C5CE7",
        "is_default": True,
        "is_preview": False,
    },
    # ── RANG #8 — FLUX.2 Flex ────────────────────────────────────────────────
    {
        "slug": "flux2_flex",
        "name": "FLUX.2 Flex",
        "provider_type": "fal_generic",
        "fal_endpoint": "fal-ai/flux-2-flex",
        "price_per_image": 0.060,
        "price_label": "$0.06 / Bild",
        "cost_tier": "premium",
        "elo_score": 1179,
        "elo_rank": 8,
        "elo_source": "Artificial Analysis Arena (März 2026)",
        "quality_stars": 5,
        "speed_seconds": 7,
        "best_for": ["hero", "general", "portrait"],
        "description": "FLUX.2 Flex, Rang #8 weltweit (Elo 1179). Vielseitig, flexibel konfigurierbar.",
        "badge": "Rang #8",
        "badge_color": "#00B894",
        "is_default": False,
        "is_preview": False,
    },
    # ── RANG #10 — Imagen 4 Ultra ─────────────────────────────────────────────
    {
        "slug": "imagen4_ultra",
        "name": "Imagen 4 Ultra",
        "provider_type": "fal_generic",
        "fal_endpoint": "fal-ai/imagen4/preview/ultra",
        "price_per_image": 0.060,
        "price_label": "$0.06 / Bild",
        "cost_tier": "premium",
        "elo_score": 1173,
        "elo_rank": 10,
        "elo_source": "Artificial Analysis Arena (März 2026)",
        "quality_stars": 5,
        "speed_seconds": 10,
        "best_for": ["hero", "portrait", "premium"],
        "description": "Googles Imagen 4 Ultra, Rang #10 (Elo 1173). Höchste Auflösung und Detailtreue der Imagen-Familie.",
        "badge": "Rang #10",
        "badge_color": "#4285F4",
        "is_default": False,
        "is_preview": False,
    },
    # ── RANG #11 — Seedream 4.5 ───────────────────────────────────────────────
    {
        "slug": "seedream_45",
        "name": "Seedream 4.5",
        "provider_type": "fal_generic",
        "fal_endpoint": "fal-ai/bytedance/seedream/v4.5/text-to-image",
        "price_per_image": 0.040,
        "price_label": "$0.04 / Bild",
        "cost_tier": "standard",
        "elo_score": 1172,
        "elo_rank": 11,
        "elo_source": "Artificial Analysis Arena (März 2026)",
        "quality_stars": 5,
        "speed_seconds": 6,
        "best_for": ["portrait", "general"],
        "description": "ByteDance Seedream 4.5, Rang #11 (Elo 1172). Exzellente Porträtqualität und natürliche Hauttöne.",
        "badge": "Geheimtipp",
        "badge_color": "#FD79A8",
        "is_default": False,
        "is_preview": False,
    },
    # ── RANG #12 — Imagen 4 Standard ─────────────────────────────────────────
    {
        "slug": "imagen4_standard",
        "name": "Imagen 4 Standard",
        "provider_type": "fal_generic",
        "fal_endpoint": "fal-ai/imagen4/preview",
        "price_per_image": 0.040,
        "price_label": "$0.04 / Bild",
        "cost_tier": "standard",
        "elo_score": 1169,
        "elo_rank": 12,
        "elo_source": "Artificial Analysis Arena (März 2026)",
        "quality_stars": 4,
        "speed_seconds": 8,
        "best_for": ["general", "hero"],
        "description": "Googles Imagen 4 Standard, Rang #12 (Elo 1169). Zuverlässige Google-Qualität zum Standard-Preis.",
        "badge": None,
        "badge_color": None,
        "is_default": False,
        "is_preview": False,
    },
    # ── RANG #14 — FLUX.2 Turbo ───────────────────────────────────────────────
    {
        "slug": "flux2_turbo",
        "name": "FLUX.2 Dev Turbo",
        "provider_type": "fal_generic",
        "fal_endpoint": "fal-ai/flux-2/turbo",
        "price_per_image": 0.008,
        "price_label": "$0.008 / Bild",
        "cost_tier": "budget",
        "elo_score": 1165,
        "elo_rank": 14,
        "elo_source": "Artificial Analysis Arena (März 2026)",
        "quality_stars": 4,
        "speed_seconds": 3,
        "best_for": ["bulk", "social_media", "ab_test"],
        "description": "Rang #14 (Elo 1165) zum Budget-Preis von $8/1.000 Bilder. Ideal für Social Media und Massenproduktion.",
        "badge": "Günstigste Top-15",
        "badge_color": "#55EFC4",
        "is_default": False,
        "is_preview": False,
    },
    # ── RANG #15 — Nano Banana (Gemini 2.5 Flash) ─────────────────────────────
    {
        "slug": "nano_banana",
        "name": "Nano Banana (Gemini 2.5 Flash)",
        "provider_type": "fal_generic",
        "fal_endpoint": "fal-ai/nano-banana",
        "price_per_image": 0.039,
        "price_label": "$0.039 / Bild",
        "cost_tier": "standard",
        "elo_score": 1164,
        "elo_rank": 15,
        "elo_source": "Artificial Analysis Arena (März 2026)",
        "quality_stars": 4,
        "speed_seconds": 6,
        "best_for": ["general", "portrait", "social_media"],
        "description": "Googles Gemini 2.5 Flash Image, Rang #15 (Elo 1164). Gutes Preis-Leistungs-Verhältnis im Mittelfeld.",
        "badge": None,
        "badge_color": None,
        "is_default": False,
        "is_preview": False,
    },
    # ── RANG #24 — FLUX.2 Klein ───────────────────────────────────────────────
    {
        "slug": "flux2_klein",
        "name": "FLUX.2 Klein 9B",
        "provider_type": "fal_generic",
        "fal_endpoint": "fal-ai/flux-2/klein/9b",
        "price_per_image": 0.015,
        "price_label": "$0.015 / Bild",
        "cost_tier": "budget",
        "elo_score": 1134,
        "elo_rank": 24,
        "elo_source": "Artificial Analysis Arena (März 2026)",
        "quality_stars": 3,
        "speed_seconds": 4,
        "best_for": ["bulk", "social_media", "general"],
        "description": "FLUX.2 Klein 9B, Rang #24 (Elo 1134). Kompaktes Modell mit guter Qualität zu niedrigen Kosten.",
        "badge": None,
        "badge_color": None,
        "is_default": False,
        "is_preview": False,
    },
    # ── TEXT OVERLAY ──────────────────────────────────────────────────────────
    {
        "slug": "ideogram_v3",
        "name": "Ideogram V3",
        "provider_type": "fal_generic",
        "fal_endpoint": "fal-ai/ideogram/v3",
        "price_per_image": 0.030,
        "price_label": "$0.03 / Bild",
        "cost_tier": "standard",
        "elo_score": None,
        "elo_rank": None,
        "elo_source": None,
        "quality_stars": 4,
        "speed_seconds": 20,
        "best_for": ["text_overlay", "poster", "schedule"],
        "description": "Spezialisiert auf Bilder mit eingebettetem Text. Sportkurspläne, Angebote, Poster mit lesbarem Text.",
        "badge": "Texte in Bildern",
        "badge_color": "#FDCB6E",
        "is_default": False,
        "is_preview": False,
    },
    # ── MARKEN & DESIGN ───────────────────────────────────────────────────────
    {
        "slug": "recraft_v4",
        "name": "Recraft V4",
        "provider_type": "fal_generic",
        "fal_endpoint": "fal-ai/recraft/v4/text-to-image",
        "price_per_image": 0.040,
        "price_label": "$0.04 / Bild",
        "cost_tier": "standard",
        "elo_score": 1093,
        "elo_rank": 33,
        "elo_source": "Artificial Analysis Arena (März 2026)",
        "quality_stars": 3,
        "speed_seconds": 40,
        "best_for": ["text_overlay", "brand_style", "design"],
        "description": "Recraft V4, Rang #33 (Elo 1093). Stärken: Logo, Design-Assets und Marken-Konsistenz.",
        "badge": "Marken & Design",
        "badge_color": "#00CEC9",
        "is_default": False,
        "is_preview": False,
        "speed_note": "Langsam (~40s) — nur für finale Brand-Assets",
    },
    # ── VORSCHAU ──────────────────────────────────────────────────────────────
    {
        "slug": "fal_ai_schnell",
        "name": "FLUX Schnell (Vorschau)",
        "provider_type": "fal_ai_schnell",
        "fal_endpoint": "fal-ai/flux/schnell",
        "price_per_image": 0.003,
        "price_label": "$0.003 / Bild",
        "cost_tier": "preview",
        "elo_score": None,
        "elo_rank": None,
        "elo_source": None,
        "quality_stars": 2,
        "speed_seconds": 2,
        "best_for": ["preview"],
        "description": "Nur für schnelle Vorschau-Generierung. Nicht für finale Kampagnen-Assets geeignet.",
        "badge": "Nur Vorschau",
        "badge_color": "#636E72",
        "is_default": False,
        "is_preview": True,
    },
]

# Quick lookup by slug
MODELS_BY_SLUG: dict[str, dict] = {m["slug"]: m for m in IMAGE_MODELS_CATALOG}

# Only production-ready (non-preview) selectable models
SELECTABLE_MODELS: list[dict] = [m for m in IMAGE_MODELS_CATALOG if not m.get("is_preview")]


def get_model_meta(slug: str) -> Optional[dict]:
    return MODELS_BY_SLUG.get(slug)
