"""Static metadata for all supported image generation models.

Source rankings: Artificial Analysis Text-to-Image Leaderboard (Elo-based),
blind pairwise user preference tests (millions of votes).
Pricing: fal.ai pricing page (March 2026).
"""
from __future__ import annotations
from typing import Optional

IMAGE_MODELS_CATALOG: list[dict] = [
    # ── RANG #1 ──────────────────────────────────────────────────────────────
    {
        "slug": "gemini_flash",
        "name": "Gemini 3.1 Flash (Nano Banana 2)",
        "provider_type": "fal_generic",
        "fal_endpoint": "fal-ai/gemini-3.1-flash-image-preview",
        "price_per_image": 0.067,
        "price_label": "$0.067 / Bild",
        "cost_tier": "premium",
        "cost_multiplier": 2.2,
        "elo_score": 1254,
        "elo_rank": 1,
        "elo_source": "Artificial Analysis Arena (März 2026)",
        "quality_stars": 5,
        "speed_seconds": 8,
        "best_for": ["hero", "portrait", "general"],
        "description": "Weltbester Text-to-Image Rang #1 (Elo 1254). Googles Gemini 3.1 Flash — unschlagbare Qualität für Hero-Bilder.",
        "badge": "Rang #1 Weltweit",
        "badge_color": "#FFD700",
        "is_default": False,
        "is_preview": False,
        "content_warning": None,
    },
    # ── RANG #2 (zu teuer) ────────────────────────────────────────────────────
    {
        "slug": "gemini_pro",
        "name": "Gemini 3 Pro (Nano Banana Pro)",
        "provider_type": "fal_generic",
        "fal_endpoint": "fal-ai/gemini-3-pro-image-preview",
        "price_per_image": 0.134,
        "price_label": "$0.134 / Bild",
        "cost_tier": "expensive",
        "cost_multiplier": 4.5,
        "elo_score": 1235,
        "elo_rank": 2,
        "elo_source": "Artificial Analysis Arena (März 2026)",
        "quality_stars": 5,
        "speed_seconds": 10,
        "best_for": ["hero", "premium"],
        "description": "Rang #2 weltweit (Elo 1235). Exzellente Qualität, aber sehr teuer.",
        "badge": "Rang #2",
        "badge_color": "#C0C0C0",
        "is_default": False,
        "is_preview": False,
        "cost_note": "⚠️ Teuer: $134/1.000 Bilder — nur für absolut kritische Assets",
        "content_warning": None,
    },
    # ── RANG #3 (zu teuer) ────────────────────────────────────────────────────
    {
        "slug": "gpt_image_15",
        "name": "GPT Image 1.5 (High)",
        "provider_type": "fal_generic",
        "fal_endpoint": "fal-ai/gpt-image-1.5",
        "price_per_image": 0.133,
        "price_label": "$0.133 / Bild",
        "cost_tier": "expensive",
        "cost_multiplier": 4.4,
        "elo_score": 1225,
        "elo_rank": 3,
        "elo_source": "Artificial Analysis Arena (März 2026)",
        "quality_stars": 5,
        "speed_seconds": 12,
        "best_for": ["hero", "premium"],
        "description": "OpenAI GPT Image 1.5, Rang #3 (Elo 1225). Sehr hohe Qualität, aber sehr teuer.",
        "badge": "Rang #3",
        "badge_color": "#CD7F32",
        "is_default": False,
        "is_preview": False,
        "cost_note": "⚠️ Teuer: $133/1.000 Bilder — nur für absolut kritische Assets",
        "content_warning": None,
    },
    # ── RANG #4 ──────────────────────────────────────────────────────────────
    {
        "slug": "imagen4_ultra",
        "name": "Imagen 4 Ultra",
        "provider_type": "fal_generic",
        "fal_endpoint": "fal-ai/imagen4/preview/ultra",
        "price_per_image": 0.060,
        "price_label": "$0.06 / Bild",
        "cost_tier": "premium",
        "cost_multiplier": 2.0,
        "elo_score": 1202,
        "elo_rank": 4,
        "elo_source": "Artificial Analysis Arena (März 2026)",
        "quality_stars": 5,
        "speed_seconds": 10,
        "best_for": ["hero", "portrait", "premium"],
        "description": "Googles Imagen 4 Ultra, Rang #4 (Elo 1202). Höchste Auflösung und Detailtreue der Imagen-Familie.",
        "badge": "Rang #4",
        "badge_color": "#4285F4",
        "is_default": False,
        "is_preview": False,
        "content_warning": None,
    },
    # ── RANG #6 — Empfehlung ─────────────────────────────────────────────────
    {
        "slug": "flux2_pro",
        "name": "FLUX.2 Pro",
        "provider_type": "fal_generic",
        "fal_endpoint": "fal-ai/flux-2-pro",
        "price_per_image": 0.030,
        "price_label": "$0.03 / Bild",
        "cost_tier": "standard",
        "cost_multiplier": 1.0,
        "elo_score": 1197,
        "elo_rank": 6,
        "elo_source": "Artificial Analysis Arena (März 2026)",
        "quality_stars": 5,
        "speed_seconds": 5,
        "best_for": ["hero", "portrait", "general"],
        "description": "Bestes Preis-Leistungs-Verhältnis 2026. Rang #6 weltweit (Elo 1197). Produktionsreif, kein Tuning nötig.",
        "badge": "Empfohlen",
        "badge_color": "#6C5CE7",
        "is_default": True,
        "is_preview": False,
        "content_warning": None,
    },
    # ── RANG #8 ──────────────────────────────────────────────────────────────
    {
        "slug": "seedream_45",
        "name": "Seedream 4.5",
        "provider_type": "fal_generic",
        "fal_endpoint": "fal-ai/bytedance/seedream/v4.5/text-to-image",
        "price_per_image": 0.040,
        "price_label": "$0.04 / Bild",
        "cost_tier": "standard",
        "cost_multiplier": 1.33,
        "elo_score": 1167,
        "elo_rank": 8,
        "elo_source": "Artificial Analysis Arena (März 2026)",
        "quality_stars": 5,
        "speed_seconds": 6,
        "best_for": ["portrait", "general"],
        "description": "ByteDance Seedream 4.5, Rang #8 (Elo 1167). Exzellente Porträtqualität und natürliche Hauttöne.",
        "badge": "Geheimtipp",
        "badge_color": "#FD79A8",
        "is_default": False,
        "is_preview": False,
        "content_warning": None,
    },
    # ── RANG #11 — Günstig ───────────────────────────────────────────────────
    {
        "slug": "flux2_turbo",
        "name": "FLUX.2 Dev Turbo",
        "provider_type": "fal_generic",
        "fal_endpoint": "fal-ai/flux-2/turbo",
        "price_per_image": 0.008,
        "price_label": "$0.008 / Bild",
        "cost_tier": "budget",
        "cost_multiplier": 0.27,
        "elo_score": 1154,
        "elo_rank": 11,
        "elo_source": "Artificial Analysis Arena (März 2026)",
        "quality_stars": 4,
        "speed_seconds": 3,
        "best_for": ["bulk", "social_media", "ab_test"],
        "description": "Rang #11 (Elo 1154) zum Budget-Preis von $8/1.000 Bilder. Ideal für Social Media und Massenproduktion.",
        "badge": "Günstigste Top-11",
        "badge_color": "#55EFC4",
        "is_default": False,
        "is_preview": False,
        "content_warning": None,
    },
    # ── RANG #12 ─────────────────────────────────────────────────────────────
    {
        "slug": "flux2_klein",
        "name": "FLUX.2 Klein 9B",
        "provider_type": "fal_generic",
        "fal_endpoint": "fal-ai/flux-2/klein/9b",
        "price_per_image": 0.015,
        "price_label": "$0.015 / Bild",
        "cost_tier": "budget",
        "cost_multiplier": 0.5,
        "elo_score": 1152,
        "elo_rank": 12,
        "elo_source": "Artificial Analysis Arena (März 2026)",
        "quality_stars": 4,
        "speed_seconds": 4,
        "best_for": ["bulk", "social_media", "general"],
        "description": "FLUX.2 Klein 9B, Rang #12 (Elo 1152). Kompaktes Modell mit Top-12-Qualität zu niedrigen Kosten.",
        "badge": None,
        "badge_color": None,
        "is_default": False,
        "is_preview": False,
        "content_warning": None,
    },
    # ── RANG #17 ─────────────────────────────────────────────────────────────
    {
        "slug": "imagen4_standard",
        "name": "Imagen 4 Standard",
        "provider_type": "fal_generic",
        "fal_endpoint": "fal-ai/imagen4/preview",
        "price_per_image": 0.040,
        "price_label": "$0.04 / Bild",
        "cost_tier": "standard",
        "cost_multiplier": 1.33,
        "elo_score": 1140,
        "elo_rank": 17,
        "elo_source": "Artificial Analysis Arena (März 2026)",
        "quality_stars": 4,
        "speed_seconds": 8,
        "best_for": ["general", "hero"],
        "description": "Googles Imagen 4 Standard, Rang #17 (Elo 1140). Zuverlässige Google-Qualität zum Standard-Preis.",
        "badge": None,
        "badge_color": None,
        "is_default": False,
        "is_preview": False,
        "content_warning": None,
    },
    # ── TEXT OVERLAY ─────────────────────────────────────────────────────────
    {
        "slug": "ideogram_v3",
        "name": "Ideogram V3",
        "provider_type": "fal_generic",
        "fal_endpoint": "fal-ai/ideogram/v3",
        "price_per_image": 0.030,
        "price_label": "$0.03 / Bild",
        "cost_tier": "standard",
        "cost_multiplier": 1.0,
        "elo_score": None,
        "elo_rank": None,
        "elo_source": None,
        "quality_stars": 4,
        "speed_seconds": 20,
        "best_for": ["text_overlay", "poster", "schedule"],
        "description": "Spezialisiert auf Bilder mit eingebettetem Text. Sportkurspläne, Angebote, Poster mit lesbarem Text.",
        "badge": "Texte in Bildern",
        "badge_color": "#FDCB6E",
        "is_default": False,
        "is_preview": False,
        "content_warning": None,
    },
    # ── RANG #33 ─────────────────────────────────────────────────────────────
    {
        "slug": "recraft_v4",
        "name": "Recraft V4",
        "provider_type": "fal_generic",
        "fal_endpoint": "fal-ai/recraft/v4/text-to-image",
        "price_per_image": 0.040,
        "price_label": "$0.04 / Bild",
        "cost_tier": "standard",
        "cost_multiplier": 1.33,
        "elo_score": 1093,
        "elo_rank": 33,
        "elo_source": "Artificial Analysis Arena (März 2026)",
        "quality_stars": 3,
        "speed_seconds": 40,
        "best_for": ["text_overlay", "brand_style", "design"],
        "description": "Recraft V4, Rang #33 (Elo 1093). Stärken: Logo, Design-Assets und Marken-Konsistenz.",
        "badge": "Marken & Design",
        "badge_color": "#00CEC9",
        "is_default": False,
        "is_preview": False,
        "speed_note": "Langsam (~40s) — nur für finale Brand-Assets",
        "content_warning": None,
    },
    # ── PREVIEW ONLY ─────────────────────────────────────────────────────────
    {
        "slug": "fal_ai_schnell",
        "name": "FLUX Schnell (Vorschau)",
        "provider_type": "fal_ai_schnell",
        "fal_endpoint": "fal-ai/flux/schnell",
        "price_per_image": 0.003,
        "price_label": "$0.003 / Bild",
        "cost_tier": "preview",
        "cost_multiplier": 0.1,
        "elo_score": None,
        "elo_rank": None,
        "elo_source": None,
        "quality_stars": 2,
        "speed_seconds": 2,
        "best_for": ["preview"],
        "description": "Nur für schnelle Vorschau-Generierung. Nicht für finale Kampagnen-Assets geeignet.",
        "badge": "Nur Vorschau",
        "badge_color": "#636E72",
        "is_default": False,
        "is_preview": True,
        "content_warning": None,
    },
]

# Quick lookup by slug
MODELS_BY_SLUG: dict[str, dict] = {m["slug"]: m for m in IMAGE_MODELS_CATALOG}

# Only production-ready (non-preview) selectable models
SELECTABLE_MODELS: list[dict] = [m for m in IMAGE_MODELS_CATALOG if not m["is_preview"]]


def get_model_meta(slug: str) -> Optional[dict]:
    return MODELS_BY_SLUG.get(slug)
