"""Static metadata for image-to-image editing models.

Source rankings: Artificial Analysis Image Editing Arena (Elo-based), März 2026.
Pricing: fal.ai pricing page (März 2026).
Last synced: 2026-03-11
"""
from __future__ import annotations
from typing import Optional

IMAGE_EDIT_MODELS_CATALOG: list[dict] = [
    # ── RANG #2 ───────────────────────────────────────────────────────────────
    {
        "slug": "gpt_image_15_edit",
        "name": "GPT Image 1.5 Edit (High)",
        "fal_endpoint": "fal-ai/gpt-image-1.5/edit",
        "price_per_image": 0.133,
        "price_label": "$0.133 / Bild",
        "cost_tier": "expensive",
        "elo_score": 1270,
        "elo_rank": 2,
        "elo_source": "Artificial Analysis Image Edit Arena (März 2026)",
        "quality_stars": 5,
        "speed_seconds": 12,
        "description": "OpenAI GPT Image 1.5 Edit, Rang #2 (Elo 1270). Höchste Edit-Qualität, aber sehr teuer.",
        "badge": "Rang #2",
        "badge_color": "#C0C0C0",
        "supports_strength": False,
        "is_default": False,
        "cost_note": "⚠️ Teuer: $133/1.000 Bilder — nur für kritische Assets",
    },
    # ── RANG #3 — Nano Banana Pro Edit ────────────────────────────────────────
    {
        "slug": "nano_banana_pro_edit",
        "name": "Nano Banana Pro Edit (Gemini 3 Pro)",
        "fal_endpoint": "fal-ai/nano-banana-pro/edit",
        "price_per_image": 0.134,
        "price_label": "$0.134 / Bild",
        "cost_tier": "expensive",
        "elo_score": 1251,
        "elo_rank": 3,
        "elo_source": "Artificial Analysis Image Edit Arena (März 2026)",
        "quality_stars": 5,
        "speed_seconds": 12,
        "description": "Googles Gemini 3 Pro Edit, Rang #3 (Elo 1251). Präzise Bildbearbeitung mit Sprachverständnis.",
        "badge": "Rang #3",
        "badge_color": "#CD7F32",
        "supports_strength": False,
        "is_default": False,
        "cost_note": "⚠️ Teuer: $134/1.000 Bilder",
    },
    # ── RANG #4 — Nano Banana 2 Edit ──────────────────────────────────────────
    {
        "slug": "nano_banana2_edit",
        "name": "Nano Banana 2 Edit (Gemini 3.1 Flash)",
        "fal_endpoint": "fal-ai/nano-banana-2/edit",
        "price_per_image": 0.067,
        "price_label": "$0.067 / Bild",
        "cost_tier": "premium",
        "elo_score": 1242,
        "elo_rank": 4,
        "elo_source": "Artificial Analysis Image Edit Arena (März 2026)",
        "quality_stars": 5,
        "speed_seconds": 8,
        "description": "Rang #4 Img2Img (Elo 1242). Googles Gemini 3.1 Flash — schnellstes Top-Edit-Modell.",
        "badge": "Rang #4 Editing",
        "badge_color": "#FFD700",
        "supports_strength": False,
        "is_default": True,
    },
    # ── RANG #9 — FLUX.2 Max Edit ─────────────────────────────────────────────
    {
        "slug": "flux2_max_edit",
        "name": "FLUX.2 Max Edit",
        "fal_endpoint": "fal-ai/flux-2-max/edit",
        "price_per_image": 0.140,
        "price_label": "$0.14 / Bild",
        "cost_tier": "expensive",
        "elo_score": 1197,
        "elo_rank": 9,
        "elo_source": "Artificial Analysis Image Edit Arena (März 2026)",
        "quality_stars": 5,
        "speed_seconds": 10,
        "description": "FLUX.2 Max Edit, Rang #9 (Elo 1197). Black Forest Labs' stärkstes Edit-Modell.",
        "badge": "Rang #9",
        "badge_color": "#4285F4",
        "supports_strength": True,
        "is_default": False,
        "cost_note": "⚠️ Teuer: $140/1.000 Bilder",
    },
    # ── RANG #10 — Seedream 4.5 Edit ─────────────────────────────────────────
    {
        "slug": "seedream_45_edit",
        "name": "Seedream 4.5 Edit",
        "fal_endpoint": "fal-ai/bytedance/seedream/v4.5/edit",
        "price_per_image": 0.040,
        "price_label": "$0.04 / Bild",
        "cost_tier": "standard",
        "elo_score": 1196,
        "elo_rank": 10,
        "elo_source": "Artificial Analysis Image Edit Arena (März 2026)",
        "quality_stars": 4,
        "speed_seconds": 6,
        "description": "ByteDance Seedream 4.5 Edit, Rang #10 (Elo 1196). Bestes Preis-Leistungs-Verhältnis im Edit-Segment.",
        "badge": "Günstig & Gut",
        "badge_color": "#FD79A8",
        "supports_strength": True,
        "is_default": False,
    },
    # ── RANG #16 — Nano Banana Edit ───────────────────────────────────────────
    {
        "slug": "nano_banana_edit",
        "name": "Nano Banana Edit (Gemini 2.5 Flash)",
        "fal_endpoint": "fal-ai/nano-banana/edit",
        "price_per_image": 0.039,
        "price_label": "$0.039 / Bild",
        "cost_tier": "standard",
        "elo_score": 1182,
        "elo_rank": 16,
        "elo_source": "Artificial Analysis Image Edit Arena (März 2026)",
        "quality_stars": 4,
        "speed_seconds": 7,
        "description": "Gemini 2.5 Flash Edit, Rang #16 (Elo 1182). Gutes Preis-Leistungs-Verhältnis.",
        "badge": None,
        "badge_color": None,
        "supports_strength": False,
        "is_default": False,
    },
    # ── RANG #17 — FLUX.2 Pro Edit ────────────────────────────────────────────
    {
        "slug": "flux2_pro_edit",
        "name": "FLUX.2 Pro Edit",
        "fal_endpoint": "fal-ai/flux-2-pro/edit",
        "price_per_image": 0.045,
        "price_label": "$0.045 / Bild",
        "cost_tier": "standard",
        "elo_score": 1174,
        "elo_rank": 17,
        "elo_source": "Artificial Analysis Image Edit Arena (März 2026)",
        "quality_stars": 4,
        "speed_seconds": 6,
        "description": "FLUX.2 Pro Edit, Rang #17 (Elo 1174). Professionelle Bildbearbeitung zu moderatem Preis.",
        "badge": None,
        "badge_color": None,
        "supports_strength": True,
        "is_default": False,
    },
    # ── RANG #18 — FLUX.2 Flex Edit ───────────────────────────────────────────
    {
        "slug": "flux2_flex_edit",
        "name": "FLUX.2 Flex Edit",
        "fal_endpoint": "fal-ai/flux-2-flex/edit",
        "price_per_image": 0.120,
        "price_label": "$0.12 / Bild",
        "cost_tier": "expensive",
        "elo_score": 1172,
        "elo_rank": 18,
        "elo_source": "Artificial Analysis Image Edit Arena (März 2026)",
        "quality_stars": 4,
        "speed_seconds": 8,
        "description": "FLUX.2 Flex Edit, Rang #18 (Elo 1172). Flexibel konfigurierbar für spezielle Anforderungen.",
        "badge": None,
        "badge_color": None,
        "supports_strength": True,
        "is_default": False,
    },
    # ── KONTEXT ───────────────────────────────────────────────────────────────
    {
        "slug": "flux_kontext_pro",
        "name": "FLUX.1 Kontext Pro",
        "fal_endpoint": "fal-ai/flux-pro/kontext",
        "price_per_image": 0.040,
        "price_label": "$0.04 / Bild",
        "cost_tier": "standard",
        "elo_score": 908,
        "elo_rank": None,
        "elo_source": "Artificial Analysis Image Edit Arena (März 2026)",
        "quality_stars": 4,
        "speed_seconds": 10,
        "description": "FLUX.1 Kontext Pro — spezialisiert auf lokale Bildbearbeitung mit exakter Texttreue.",
        "badge": "Kontextuell",
        "badge_color": "#6C5CE7",
        "supports_strength": True,
        "is_default": False,
    },
    # ── BUDGET ────────────────────────────────────────────────────────────────
    {
        "slug": "flux2_flash_edit",
        "name": "FLUX.2 Dev Flash Edit",
        "fal_endpoint": "fal-ai/flux-2/flash/edit",
        "price_per_image": 0.005,
        "price_label": "$0.005 / Bild",
        "cost_tier": "budget",
        "elo_score": None,
        "elo_rank": None,
        "elo_source": None,
        "quality_stars": 3,
        "speed_seconds": 2,
        "description": "FLUX.2 Dev Flash Edit, $5/1.000 Bilder — ideal für schnelle Iterationen und Tests.",
        "badge": "Günstigstes Edit",
        "badge_color": "#55EFC4",
        "supports_strength": True,
        "is_default": False,
    },
    {
        "slug": "flux2_turbo_edit",
        "name": "FLUX.2 Dev Turbo Edit",
        "fal_endpoint": "fal-ai/flux-2/turbo/edit",
        "price_per_image": 0.008,
        "price_label": "$0.008 / Bild",
        "cost_tier": "budget",
        "elo_score": None,
        "elo_rank": None,
        "elo_source": None,
        "quality_stars": 3,
        "speed_seconds": 3,
        "description": "FLUX.2 Dev Turbo Edit, $8/1.000 Bilder.",
        "badge": None,
        "badge_color": None,
        "supports_strength": True,
        "is_default": False,
    },
]

EDIT_MODELS_BY_SLUG: dict[str, dict] = {m["slug"]: m for m in IMAGE_EDIT_MODELS_CATALOG}
SELECTABLE_EDIT_MODELS: list[dict] = IMAGE_EDIT_MODELS_CATALOG


def get_edit_model_meta(slug: str) -> Optional[dict]:
    return EDIT_MODELS_BY_SLUG.get(slug)
