"""Static metadata for all supported image generation models.

Source rankings: Artificial Analysis Text-to-Image Leaderboard (Elo-based),
blind pairwise user preference tests (millions of votes).
Pricing: fal.ai pricing page (March 2026).
"""
from __future__ import annotations
from typing import Optional

IMAGE_MODELS_CATALOG: list[dict] = [
    # ── TOP TIER ────────────────────────────────────────────────────────────
    {
        "slug": "flux2_pro",
        "name": "FLUX.2 Pro",
        "provider_type": "fal_generic",
        "fal_endpoint": "fal-ai/flux-2-pro",
        "price_per_image": 0.030,
        "price_label": "$0.03 / Bild",
        "cost_tier": "standard",          # standard | premium | expensive
        "cost_multiplier": 1.0,           # relative to cheapest tier (schnell)
        "elo_score": 1153,
        "elo_rank": 6,
        "elo_source": "Artificial Analysis Arena (März 2026)",
        "quality_stars": 5,               # 1-5 for UI display
        "speed_seconds": 5,               # approx generation time
        "best_for": ["hero", "portrait", "general"],
        "description": "Bestes Preis-Leistungs-Verhältnis 2026. Globaler Rang #6 nach Elo. Produktionsreif, kein Tuning nötig.",
        "badge": "Empfohlen",
        "badge_color": "#6C5CE7",
        "is_default": True,
        "is_preview": False,
        "content_warning": None,
    },
    {
        "slug": "flux2_max",
        "name": "FLUX.2 Max",
        "provider_type": "fal_generic",
        "fal_endpoint": "fal-ai/flux-2-max",
        "price_per_image": 0.070,
        "price_label": "$0.07 / Bild",
        "cost_tier": "premium",
        "cost_multiplier": 2.3,
        "elo_score": 1168,
        "elo_rank": 3,
        "elo_source": "Artificial Analysis Arena (März 2026)",
        "quality_stars": 5,
        "speed_seconds": 10,
        "best_for": ["hero", "portrait", "premium"],
        "description": "Höchste Qualität der FLUX-Familie. Globaler Rang #3. Beste Hautstruktur & Anatomie.",
        "badge": "Beste Qualität",
        "badge_color": "#00B87A",
        "is_default": False,
        "is_preview": False,
        "cost_note": "2,3× teurer als FLUX.2 Pro — empfohlen nur für Hero-Bilder",
        "content_warning": None,
    },
    {
        "slug": "flux2_flex",
        "name": "FLUX.2 Flex",
        "provider_type": "fal_generic",
        "fal_endpoint": "fal-ai/flux-2-flex",
        "price_per_image": 0.060,
        "price_label": "$0.06 / Bild",
        "cost_tier": "premium",
        "cost_multiplier": 2.0,
        "elo_score": 1157,
        "elo_rank": 4,
        "elo_source": "Artificial Analysis Arena (März 2026)",
        "quality_stars": 5,
        "speed_seconds": 7,
        "best_for": ["hero", "creative", "ab_test"],
        "description": "Flexibel steuerbar mit Referenzbildern. Globaler Rang #4. Ideal für A/B-Tests mit verschiedenen Stilen.",
        "badge": None,
        "badge_color": None,
        "is_default": False,
        "is_preview": False,
        "cost_note": "2× teurer als FLUX.2 Pro",
        "content_warning": None,
    },
    {
        "slug": "seedream_45",
        "name": "Seedream 4.5",
        "provider_type": "fal_generic",
        "fal_endpoint": "fal-ai/bytedance/seedream/v4.5/text-to-image",
        "price_per_image": 0.040,
        "price_label": "$0.04 / Bild",
        "cost_tier": "standard",
        "cost_multiplier": 1.33,
        "elo_score": 1147,
        "elo_rank": 9,
        "elo_source": "Artificial Analysis Arena (März 2026)",
        "quality_stars": 4,
        "speed_seconds": 6,
        "best_for": ["portrait", "general"],
        "description": "Globaler Rang #9. Exzellente Porträtqualität und natürliche Hauttöne bei $0.04.",
        "badge": "Geheimtipp",
        "badge_color": "#FD79A8",
        "is_default": False,
        "is_preview": False,
        "content_warning": None,
    },
    # ── TEXT OVERLAY ────────────────────────────────────────────────────────
    {
        "slug": "recraft_v3",
        "name": "Recraft V3",
        "provider_type": "recraft_v3",
        "fal_endpoint": "fal-ai/recraft-v3",
        "price_per_image": 0.040,
        "price_label": "$0.04 / Bild",
        "cost_tier": "standard",
        "cost_multiplier": 1.33,
        "elo_score": 1138,
        "elo_rank": 12,
        "elo_source": "Artificial Analysis (5× #1 Benchmark 2024)",
        "quality_stars": 4,
        "speed_seconds": 40,
        "best_for": ["text_overlay", "brand_style", "poster"],
        "description": "5 Monate lang #1 auf Hugging Face Benchmark. Beste Typografie & Marken-Konsistenz.",
        "badge": "Texte in Bildern",
        "badge_color": "#FDCB6E",
        "is_default": False,
        "is_preview": False,
        "speed_note": "Langsam (~40s) — für finale Bilder mit Text",
        "content_warning": None,
    },
    {
        "slug": "recraft_v4",
        "name": "Recraft V4",
        "provider_type": "fal_generic",
        "fal_endpoint": "fal-ai/recraft/v4/text-to-image",
        "price_per_image": 0.040,
        "price_label": "$0.04 / Bild",
        "cost_tier": "standard",
        "cost_multiplier": 1.33,
        "elo_score": None,
        "elo_rank": None,
        "elo_source": "Hugging Face Benchmark #1 (Logo & Design)",
        "quality_stars": 4,
        "speed_seconds": 40,
        "best_for": ["text_overlay", "brand_style", "design"],
        "description": "#1 für Logo & Design-Assets. Stärkere Komposition als V3. Ideal für Branding-Kampagnen.",
        "badge": "Neu",
        "badge_color": "#00CEC9",
        "is_default": False,
        "is_preview": False,
        "speed_note": "Langsam (~40s)",
        "content_warning": None,
    },
    {
        "slug": "ideogram_v3_turbo",
        "name": "Ideogram V3 Turbo",
        "provider_type": "fal_generic",
        "fal_endpoint": "fal-ai/ideogram/v3",
        "fal_params": {"rendering_speed": "TURBO"},
        "price_per_image": 0.030,
        "price_label": "$0.03 / Bild",
        "cost_tier": "standard",
        "cost_multiplier": 1.0,
        "elo_score": None,
        "elo_rank": None,
        "elo_source": None,
        "quality_stars": 3,
        "speed_seconds": 20,
        "best_for": ["text_overlay", "poster", "schedule"],
        "description": "Günstigste Option für Bilder mit eingebettetem Text. Sportkurspläne, Angebote, Poster.",
        "badge": None,
        "badge_color": None,
        "is_default": False,
        "is_preview": False,
        "content_warning": None,
    },
    # ── SPECIALIZED ─────────────────────────────────────────────────────────
    {
        "slug": "flux_pro_ultra",
        "name": "FLUX 1.1 Pro Ultra (Raw)",
        "provider_type": "fal_generic",
        "fal_endpoint": "fal-ai/flux-pro/v1.1-ultra",
        "fal_params": {"raw": True},
        "price_per_image": 0.060,
        "price_label": "$0.06 / Bild",
        "cost_tier": "premium",
        "cost_multiplier": 2.0,
        "elo_score": 1143,
        "elo_rank": None,
        "elo_source": "fal.ai Benchmark",
        "quality_stars": 4,
        "speed_seconds": 10,
        "best_for": ["authentic", "documentary", "print"],
        "description": "Raw Mode reduziert KI-Gloss — authentisches, dokumentarisches Look für echtes Fitness-Flair. 4MP (2048²) für Printqualität.",
        "badge": "Authentisch",
        "badge_color": "#E17055",
        "is_default": False,
        "is_preview": False,
        "cost_note": "2× teurer als FLUX.2 Pro",
        "content_warning": None,
    },
    {
        "slug": "hidream_fast",
        "name": "HiDream I1 Fast",
        "provider_type": "fal_generic",
        "fal_endpoint": "fal-ai/hidream-i1-fast",
        "price_per_image": 0.010,
        "price_label": "$0.01 / Bild",
        "cost_tier": "budget",
        "cost_multiplier": 0.33,
        "elo_score": None,
        "elo_rank": None,
        "elo_source": None,
        "quality_stars": 3,
        "speed_seconds": 4,
        "best_for": ["bulk", "social_media", "preview"],
        "description": "17B Open-Source Modell. Günstigstes Qualitätsmodell für Social-Media-Massenproduktion.",
        "badge": "Günstigste Wahl",
        "badge_color": "#55EFC4",
        "is_default": False,
        "is_preview": False,
        "content_warning": None,
    },
    # ── PREVIEW ONLY ────────────────────────────────────────────────────────
    {
        "slug": "fal_ai_schnell",
        "name": "FLUX Schnell (Vorschau)",
        "provider_type": "fal_ai_schnell",
        "fal_endpoint": "fal-ai/flux/schnell",
        "price_per_image": 0.003,
        "price_label": "$0.003 / Bild",
        "cost_tier": "preview",
        "cost_multiplier": 0.1,
        "elo_score": None,
        "elo_rank": None,
        "elo_source": None,
        "quality_stars": 2,
        "speed_seconds": 2,
        "best_for": ["preview"],
        "description": "Nur für schnelle Vorschau-Generierung. Nicht für finale Kampagnen-Assets geeignet.",
        "badge": "Nur Vorschau",
        "badge_color": "#636E72",
        "is_default": False,
        "is_preview": True,
        "content_warning": None,
    },
]

# Quick lookup by slug
MODELS_BY_SLUG: dict[str, dict] = {m["slug"]: m for m in IMAGE_MODELS_CATALOG}

# Only production-ready (non-preview) selectable models
SELECTABLE_MODELS: list[dict] = [m for m in IMAGE_MODELS_CATALOG if not m["is_preview"]]


def get_model_meta(slug: str) -> Optional[dict]:
    return MODELS_BY_SLUG.get(slug)
