"""Initial schema and default=1 removal

Revision ID: 42f8a7fcb1f9
Revises: 
Create Date: 2026-02-22 03:26:19.988256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42f8a7fcb1f9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_messages', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_chat_messages_tenant_id'), 'chat_messages', ['tenant_id'], unique=False)
    op.alter_column('chat_sessions', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_tenant_id'), 'chat_sessions', ['tenant_id'], unique=False)
    op.alter_column('settings', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_settings_tenant_id'), 'settings', ['tenant_id'], unique=False)
    op.alter_column('studio_members', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_studio_members_customer_id'), table_name='studio_members')
    op.create_index(op.f('ix_studio_members_customer_id'), 'studio_members', ['customer_id'], unique=False)
    op.create_index(op.f('ix_studio_members_tenant_id'), 'studio_members', ['tenant_id'], unique=False)
    op.drop_column('studio_members', 'pause_reason')
    op.drop_column('studio_members', 'idle_history')
    op.drop_column('studio_members', 'contract_name')
    op.drop_column('studio_members', 'contract_price')
    op.drop_column('studio_members', 'payment_method')
    op.drop_column('studio_members', 'pause_until')
    op.drop_column('studio_members', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studio_members', sa.Column('address', sa.TEXT(), nullable=True))
    op.add_column('studio_members', sa.Column('pause_until', sa.DATE(), nullable=True))
    op.add_column('studio_members', sa.Column('payment_method', sa.VARCHAR(), nullable=True))
    op.add_column('studio_members', sa.Column('contract_price', sa.REAL(), nullable=True))
    op.add_column('studio_members', sa.Column('contract_name', sa.VARCHAR(), nullable=True))
    op.add_column('studio_members', sa.Column('idle_history', sa.TEXT(), nullable=True))
    op.add_column('studio_members', sa.Column('pause_reason', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_studio_members_tenant_id'), table_name='studio_members')
    op.drop_index(op.f('ix_studio_members_customer_id'), table_name='studio_members')
    op.create_index(op.f('ix_studio_members_customer_id'), 'studio_members', ['customer_id'], unique=1)
    op.alter_column('studio_members', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_settings_tenant_id'), table_name='settings')
    op.alter_column('settings', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_chat_sessions_tenant_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=1)
    op.alter_column('chat_sessions', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_chat_messages_tenant_id'), table_name='chat_messages')
    op.alter_column('chat_messages', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
