"""Initial schema migration

Revision ID: 4f31e5c56744
Revises: 42f8a7fcb1f9
Create Date: 2026-02-22 03:32:09.258138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f31e5c56744'
down_revision: Union[str, None] = '42f8a7fcb1f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### Data Migration (Set NULL tenant_id to 1) ###
    conn = op.get_bind()
    conn.execute(sa.text("UPDATE chat_messages SET tenant_id = 1 WHERE tenant_id IS NULL"))
    conn.execute(sa.text("UPDATE chat_sessions SET tenant_id = 1 WHERE tenant_id IS NULL"))
    conn.execute(sa.text("UPDATE settings SET tenant_id = 1 WHERE tenant_id IS NULL"))
    conn.execute(sa.text("UPDATE studio_members SET tenant_id = 1 WHERE tenant_id IS NULL"))
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_chat_sessions_user_id'))
        batch_op.create_index(batch_op.f('ix_chat_sessions_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_sessions_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_settings_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('studio_members', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_studio_members_customer_id'))
        batch_op.create_index(batch_op.f('ix_studio_members_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_studio_members_tenant_id'), ['tenant_id'], unique=False)
        batch_op.drop_column('contract_price')
        batch_op.drop_column('idle_history')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('address')
        batch_op.drop_column('pause_until')
        batch_op.drop_column('contract_name')
        batch_op.drop_column('pause_reason')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('studio_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pause_reason', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('contract_name', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('pause_until', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('address', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('idle_history', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('contract_price', sa.REAL(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_studio_members_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_studio_members_customer_id'))
        batch_op.create_index(batch_op.f('ix_studio_members_customer_id'), ['customer_id'], unique=1)
        batch_op.alter_column('tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settings_tenant_id'))
        batch_op.alter_column('tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_sessions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_chat_sessions_user_id'))
        batch_op.create_index(batch_op.f('ix_chat_sessions_user_id'), ['user_id'], unique=1)
        batch_op.alter_column('tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_tenant_id'))
        batch_op.alter_column('tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
