"""add member feedback table

Revision ID: fadf7c20edd1
Revises: a1b2c3d4e5f6
Create Date: 2026-02-22 12:02:51.055738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fadf7c20edd1'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('member_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_member_feedback_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_member_feedback_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_member_feedback_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('tenant_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenant_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenant_configs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenant_configs_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenant_configs_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_audit_logs_tenant'), type_='foreignkey')

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_tenant_id'), ['tenant_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_chat_messages_tenant'), type_='foreignkey')

    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_chat_sessions_user_id'))
        batch_op.create_index(batch_op.f('ix_chat_sessions_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_sessions_tenant_id'), ['tenant_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_chat_sessions_tenant'), type_='foreignkey')

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_settings_tenant_id'), ['tenant_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_settings_tenant'), type_='foreignkey')

    with op.batch_alter_table('studio_members', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_studio_members_customer_id'))
        batch_op.create_index(batch_op.f('ix_studio_members_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_studio_members_tenant_id'), ['tenant_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_studio_members_tenant'), type_='foreignkey')
        batch_op.drop_column('address')
        batch_op.drop_column('pause_reason')
        batch_op.drop_column('contract_name')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('pause_until')
        batch_op.drop_column('idle_history')
        batch_op.drop_column('contract_price')

    with op.batch_alter_table('usage_records', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_usage_records_tenant'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_tenant'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_users_tenant'), 'tenants', ['tenant_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('usage_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_usage_records_tenant'), 'tenants', ['tenant_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('studio_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contract_price', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('idle_history', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('pause_until', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('contract_name', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('pause_reason', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('address', sa.TEXT(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_studio_members_tenant'), 'tenants', ['tenant_id'], ['id'], ondelete='RESTRICT')
        batch_op.drop_index(batch_op.f('ix_studio_members_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_studio_members_customer_id'))
        batch_op.create_index(batch_op.f('ix_studio_members_customer_id'), ['customer_id'], unique=1)
        batch_op.alter_column('tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_settings_tenant'), 'tenants', ['tenant_id'], ['id'], ondelete='RESTRICT')
        batch_op.drop_index(batch_op.f('ix_settings_tenant_id'))
        batch_op.alter_column('tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_chat_sessions_tenant'), 'tenants', ['tenant_id'], ['id'], ondelete='RESTRICT')
        batch_op.drop_index(batch_op.f('ix_chat_sessions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_chat_sessions_user_id'))
        batch_op.create_index(batch_op.f('ix_chat_sessions_user_id'), ['user_id'], unique=1)
        batch_op.alter_column('tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_chat_messages_tenant'), 'tenants', ['tenant_id'], ['id'], ondelete='RESTRICT')
        batch_op.drop_index(batch_op.f('ix_chat_messages_tenant_id'))
        batch_op.alter_column('tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_audit_logs_tenant'), 'tenants', ['tenant_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('tenant_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_configs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_tenant_configs_key'))
        batch_op.drop_index(batch_op.f('ix_tenant_configs_id'))

    op.drop_table('tenant_configs')
    with op.batch_alter_table('member_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_member_feedback_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_member_feedback_session_id'))
        batch_op.drop_index(batch_op.f('ix_member_feedback_id'))

    op.drop_table('member_feedback')
    # ### end Alembic commands ###
